org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options="-Xmx1024m"
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.configureondemand=true
org.gradle.daemon=false
android.useAndroidX=true
android.enableJetifier=true
android.disableAutomaticComponentCreation=true
expo.jsEngine=jsc
FLIPPER_VERSION=0.182.0
